amf.host: 10.154.14.5
amf.port: 38419
amf.mocked: true
amf.mockedRemote: mockedRemote.yaml

input.NgSetupFlow: ngsetup.yaml
input.RegistrationFlow: registration.yaml
input.PeriodicRegistrationFlow: registration.yaml
input.PduSessionEstablishmentFlow: pduSessionEstablishment.yaml
input.PduSessionReleaseFlow: pduSessionRelease.yaml
input.UEContextReleaseRequestFlow: ueContextReleaseRequest.yaml
input.ServiceRequestFlow: serviceRequest.yaml
input.DeregistrationFlow: deregistration.yaml
input.NgResetFlow: ngreset.yaml

ueData: '@ueData_i2i.yaml'

context.ranUeNgapId: 1000
context.userLocationInformationNr:
  nrCgi:
    plmn:
      mcc: 1
      mnc: 1
    nrCellIdentity:
      hex: '01b2c3d4e0'
  tai:
    mcc: 1
    mnc: 1
    tac: '000075'
  timeStamp:
    hex: 5b5fa680