amf.host: 10.154.14.5
amf.port: 38419
amf.mocked: true
amf.mockedRemote: mockedRemote.yaml

input.NgSetupFlow: ngsetup.yaml
input.RegistrationFlow: registration.yaml
input.PduSessionEstablishmentFlow: pduSessionEstablishment.yaml
input.PduSessionReleaseFlow: pduSessionRelease.yaml
input.UEContextReleaseRequestFlow: ueContextReleaseRequest.yaml
input.ServiceRequestFlow: serviceRequest.yaml
input.DeregistrationFlow: deregistration.yaml

ueData.key: '5C95978B5E89488CB7DB44381E237809'
ueData.op: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
ueData.sqn: '001000000000'
ueData.amf: '8000'
ueData.imei: '356938035643809'
ueData.snn: '5G:mnc001.mcc001.3gppnetwork.org'
ueData.supi: 'imsi-001001000000010'

context.ranUeNgapId: 1000
context.userLocationInformationNr:
  nrCgi:
    plmn:
      mcc: 1
      mnc: 1
    nrCellIdentity:
      hex: '01b2c3d4e0'
  tai:
    mcc: 1
    mnc: 1
    tac: '000075'
  timeStamp:
    hex: 5b5fa680